//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X12UtilsFRM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("X12UtilsFRM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;TransactionSpecification xmlns=&quot;http://tempuri.org/X12ParserSpecification.xsd&quot;  TransactionSetIdentifierCode=&quot;856&quot;&gt;
        ///  &lt;Segment SegmentId=&quot;BSN&quot; Repeat=&quot;1&quot;/&gt;
        ///  &lt;Segment SegmentId=&quot;DTM&quot;/&gt;
        ///  &lt;Segment SegmentId=&quot;CTT&quot; Usage=&quot;Situational&quot; Trailer=&quot;true&quot; Repeat=&quot;1&quot;/&gt;
        ///  &lt;HierarchicalLoop LoopId=&quot;SHIPMENT&quot; Usage=&quot;Required&quot; LevelCode=&quot;S&quot;&gt;
        ///    &lt;Name&gt;SHIPMENT&lt;/Name&gt;
        ///    &lt;Segment SegmentId=&quot;LIN&quot;/&gt;
        ///    &lt;Segment SegmentId=&quot;SN1&quot;/&gt;
        ///    &lt;Segment SegmentId=&quot;SLN&quot;/&gt;
        ///    &lt;Segment [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GeogiaPacific_856_4010_Specification {
            get {
                return ResourceManager.GetString("GeogiaPacific_856_4010_Specification", resourceCulture);
            }
        }
    }
}
